CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(24) UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  subscription DATE,
  hwid TEXT,
  avatar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS licenses (
  id BIGSERIAL PRIMARY KEY,
  license_key TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'unused',
  duration_days INTEGER NOT NULL DEFAULT 30,
  hwid TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS site_stats (
  id INTEGER PRIMARY KEY,
  visitors_count INTEGER NOT NULL DEFAULT 247
);
